### ISSUE TITLE
Cant start npm run dev

### ISSUE THREAD

**Issue by legitleefu** [TheHadiAhmadi/site-builder#3]
**Describe the bug**

npm run dev

> tailcms@1.0.1-next.21 dev
> node bin/tailcms.js dev

file:///home/XXXX/git/site-builder/bin/tailcms.js:105
            type: process.env.TAILCMS_DB ?? 'memory',
SyntaxError: Unexpected token '?'

**Comment by TheHadiAhmadi** [comment]
Hi @kroghdk, What is your Nodejs version?

in v20.18.0 it works.

**Comment by legitleefu** [comment]
On my server i forgot to update, it was v18~
It works now
